<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.moduledef/ru.rb.ccdea.formadaptors.PassportContragentAdaptor?name=ru.rb.ccdea.formadaptors.PassportContragentAdaptor" categoryId="com.emc.ide.artifact.moduledef" implicitlyCreated="true" modifiedByUser="false">
  <dataModel xsi:type="moduledef:ModuleDef" objectName="ru.rb.ccdea.formadaptors.PassportContragentAdaptor" title="" subject="" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" status="" min_dfc_version="" implementation_technology="" contact_info="" a_bof_version="" a_module_type="SBO" module_description="">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_module?name=dmc_module#//@dataModel"/>
    <versionLabel>1.0</versionLabel>
    <versionLabel>CURRENT</versionLabel>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/ucb_ccdea_formadaptors?language_code=&amp;location=%2FSystem%2FModules%2FSBO%2Fru.rb.ccdea.formadaptors.ContragentAdaptor&amp;name=ucb_ccdea_formadaptors&amp;type=dmc_jar#//@dataModel"/>
    <runtimeEnvironmentXML objectName="RuntimeEnvironment.xml" contentType="xml" rootObject="false" minDFCVersion="" minVmVersion="">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_sysobject?name=dm_sysobject#//@dataModel"/>
      <log message="" level="NONE"/>
    </runtimeEnvironmentXML>
    <primaryElement primary_class="ru.rb.ccdea.formadaptors.PassportContragentAdaptor"/>
    <miscellaneous objectName="Miscellaneous" title="" subject="" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" status="" rootObject="false">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_folder?name=dm_folder#//@dataModel"/>
      <versionLabel>1.0</versionLabel>
      <versionLabel>CURRENT</versionLabel>
    </miscellaneous>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
