<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.moduledef/com.documentum.services.dam.df.transform.ICTSService?name=com.documentum.services.dam.df.transform.ICTSService" categoryId="com.emc.ide.artifact.moduledef">
  <dataModel xsi:type="moduledef:ModuleDef" objectName="com.documentum.services.dam.df.transform.ICTSService" title="" subject="" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" fullText="true" status="" min_dfc_version="" implementation_technology="Java" contact_info="" a_bof_version="6.0" a_module_type="SBO" module_description="">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_module?name=dmc_module#//@dataModel"/>
    <versionLabel>1.0</versionLabel>
    <versionLabel>CURRENT</versionLabel>
    <interfaceJars href="urn:com.emc.ide.artifact.jardef.jardef/ctsTransform.jar?language_code=&amp;location=%2FSystem%2FApplications%2FTransformation%2FctsTransform&amp;name=ctsTransform.jar&amp;type=dmc_jar#//@dataModel"/>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/ctsTransformImpl.jar?language_code=&amp;location=%2FSystem%2FApplications%2FTransformation%2FctstransformImpl&amp;name=ctsTransformImpl.jar&amp;type=dmc_jar#//@dataModel"/>
    <runtimeEnvironmentXML objectName="RuntimeEnvironment.xml" contentType="xml" rootObject="false" minDFCVersion="" minVmVersion="">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_sysobject?name=dm_sysobject#//@dataModel"/>
      <log message="" level="NONE"/>
    </runtimeEnvironmentXML>
    <primaryElement primary_class="com.documentum.services.dam.impl.transform.CTSService">
      <a_interfaces>com.documentum.services.dam.df.transform.ICTSService</a_interfaces>
      <a_interfaces>com.documentum.fc.client.IDfService</a_interfaces>
      <a_interfaces>com.documentum.fc.client.IDfModule</a_interfaces>
      <a_interfaces>java.io.Serializable</a_interfaces>
    </primaryElement>
    <miscellaneous objectName="Miscellaneous" title="" subject="" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" status="" rootObject="false">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_folder?name=dm_folder#//@dataModel"/>
      <versionLabel>1.0</versionLabel>
      <versionLabel>CURRENT</versionLabel>
    </miscellaneous>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
