<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.moduledef/ucb_ccdea_content_service?artifactURI=file:/C:/Users/ER21559/composerworkspace/CCDEA_api/Artifacts/Modules/ucb_ccdea_content_service.module" categoryId="com.emc.ide.artifact.moduledef">
  <dataModel xsi:type="moduledef:ModuleDef" objectName="ucb_ccdea_content_service" a_module_type="SBO">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_module?name=dmc_module#//@dataModel"/>
    <reqModules href="urn:com.emc.ide.artifact.moduledef/com.documentum.services.cts.df.transform.ICTSAddJobService?name=com.documentum.services.cts.df.transform.ICTSAddJobService#//@dataModel"/>
    <reqModules href="urn:com.emc.ide.artifact.moduledef/com.documentum.services.cts.df.transform.ICTSTransformService?name=com.documentum.services.cts.df.transform.ICTSTransformService#//@dataModel"/>
    <reqModules href="urn:com.emc.ide.artifact.moduledef/com.documentum.services.dam.df.transform.ICTSService?name=com.documentum.services.dam.df.transform.ICTSService#//@dataModel"/>
    <reqModules href="urn:com.emc.ide.artifact.moduledef/com.documentum.services.dam.df.transform.IProfileService?name=com.documentum.services.dam.df.transform.IProfileService#//@dataModel"/>
    <interfaceJars href="urn:com.emc.ide.artifact.jardef.jardef/ucb_ccdea_services_api?artifactURI=file:/C:/Users/ER21559/composerworkspace/CCDEA_api/Artifacts/JAR%20Definitions/ucb_ccdea_services_api.jardef#//@dataModel"/>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/ucb_ccdea_services_impl?artifactURI=file:/C:/Users/ER21559/composerworkspace/CCDEA_api/Artifacts/JAR%20Definitions/ucb_ccdea_services_impl.jardef#//@dataModel"/>
    <runtimeEnvironmentXML objectName="RuntimeEnvironment.xml">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_sysobject?name=dm_sysobject#//@dataModel"/>
      <log/>
    </runtimeEnvironmentXML>
    <primaryElement primary_class="ru.rb.ccdea.storage.services.impl.ContentService">
      <a_interfaces>ru.rb.ccdea.storage.services.api.IContentService</a_interfaces>
      <a_interfaces>com.documentum.fc.client.IDfService</a_interfaces>
      <a_interfaces>com.documentum.fc.client.IDfModule</a_interfaces>
    </primaryElement>
    <thirdPartyLibraries href="urn:com.emc.ide.artifact.jardef.javalibrary/ucb_ccdea_persistence_library?artifactURI=file:/C:/Users/ER21559/composerworkspace/CCDEA_api/Artifacts/Java%20Libraries/ucb_ccdea_persistence_library.javalibrary#//@dataModel"/>
    <thirdPartyLibraries href="urn:com.emc.ide.artifact.jardef.javalibrary/ucb_ccdea_mq_binding_up_library?artifactURI=file:/C:/Users/ER21559/composerworkspace/CCDEA_api/Artifacts/Java%20Libraries/ucb_ccdea_mq_binding_up_library.javalibrary#//@dataModel"/>
    <miscellaneous objectName="Miscellaneous">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_folder?name=dm_folder#//@dataModel"/>
    </miscellaneous>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
