<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.moduledef/ucb_ccdea_docstatenotify_sender_mdl?artifactURI=file:/C:/Users/ER21559/composerworkspace/CCDEA_api/Artifacts/Modules/ucb_ccdea_docstatenotify_sender_mdl.module" categoryId="com.emc.ide.artifact.moduledef" implicitlyCreated="true" modifiedByUser="false">
  <dataModel xsi:type="moduledef:ModuleDef" objectName="ucb_ccdea_docstatenotify_sender_mdl" title="" subject="" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" status="" min_dfc_version="" implementation_technology="" contact_info="" a_bof_version="" a_module_type="[Standard Module]" module_description="">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_module?name=dmc_module#//@dataModel"/>
    <versionLabel>1.0</versionLabel>
    <versionLabel>CURRENT</versionLabel>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/ucb_ccdea_mq_adapter?artifactURI=file:/C:/Users/ER21559/composerworkspace/CCDEA_api/Artifacts/JAR%20Definitions/ucb_ccdea_mq_adapter.jardef#//@dataModel"/>
    <runtimeEnvironmentXML objectName="RuntimeEnvironment.xml" contentType="xml" rootObject="false" minDFCVersion="" minVmVersion="">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_sysobject?name=dm_sysobject#//@dataModel"/>
      <log message="" level="NONE"/>
    </runtimeEnvironmentXML>
    <primaryElement primary_class="ru.rb.ccdea.adapters.mq.senders.DocStateNotifyMethod">
      <a_interfaces>com.documentum.fc.methodserver.IDfMethod</a_interfaces>
      <a_interfaces>com.documentum.fc.client.IDfModule</a_interfaces>
      <a_interfaces>com.documentum.bpm.rtutil.IDfWorkflowTask</a_interfaces>
    </primaryElement>
    <thirdPartyLibraries href="urn:com.emc.ide.artifact.jardef.javalibrary/ucb_ccdea_persistence_library?artifactURI=file:/C:/Users/ER21559/composerworkspace/CCDEA_api/Artifacts/Java%20Libraries/ucb_ccdea_persistence_library.javalibrary#//@dataModel"/>
    <thirdPartyLibraries href="urn:com.emc.ide.artifact.jardef.javalibrary/ucb_ccdea_mq_binding_library?artifactURI=file:/C:/Users/ER21559/composerworkspace/CCDEA_api/Artifacts/Java%20Libraries/ucb_ccdea_mq_binding_library.javalibrary#//@dataModel"/>
    <miscellaneous objectName="Miscellaneous" title="" subject="" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" status="" rootObject="false">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_folder?name=dm_folder#//@dataModel"/>
      <versionLabel>1.0</versionLabel>
      <versionLabel>CURRENT</versionLabel>
    </miscellaneous>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
