<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.aspectmoduledef/com.documentum.fc.bof.bootstrap.DfModuleItemChangeMonitor?aspectname=com.documentum.fc.bof.bootstrap.DfModuleItemChangeMonitor" categoryId="com.emc.ide.artifact.aspectmoduledef">
  <dataModel xsi:type="moduledef:AspectModuleDef" objectName="com.documentum.fc.bof.bootstrap.DfModuleItemChangeMonitor">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_aspect_type?name=dmc_aspect_type#//@dataModel"/>
    <primaryElement/>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
