<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.aspectmoduledef/dm_logical_version?name=dm_logical_version" categoryId="com.emc.ide.artifact.aspectmoduledef" implicitlyCreated="true" modifiedByUser="false">
  <dataModel xsi:type="moduledef:AspectModuleDef" objectName="dm_logical_version" title="" subject="" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" status="" min_dfc_version="6.0" implementation_technology="Java" contact_info="" a_bof_version="" a_module_type="Aspect" module_description="">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_aspect_type?name=dmc_aspect_type#//@dataModel"/>
    <versionLabel>1.0</versionLabel>
    <versionLabel>CURRENT</versionLabel>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/logical-version-impl.jar?language_code=&amp;location=%2FSystem%2FModules%2FAspect%2Fdm_logical_version&amp;name=logical-version-impl.jar&amp;type=dmc_jar#//@dataModel"/>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/smartcontainer-common-impl.jar?language_code=&amp;location=%2FSystem%2FModules%2FAspect%2Fdm_annotatable&amp;name=smartcontainer-common-impl.jar&amp;type=dmc_jar#//@dataModel"/>
    <runtimeEnvironmentXML objectName="RuntimeEnvironment.xml" contentType="xml" rootObject="false" minDFCVersion="6.0" minVmVersion="1.5">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_sysobject?name=dm_sysobject#//@dataModel"/>
      <log message="" level="NONE"/>
    </runtimeEnvironmentXML>
    <primaryElement primary_class="com.documentum.smart.impl.aspect.LogicalVersionAspect"/>
    <miscellaneous objectName="Miscellaneous" title="" subject="" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" status="" rootObject="false">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_folder?name=dm_folder#//@dataModel"/>
      <versionLabel>1.0</versionLabel>
      <versionLabel>CURRENT</versionLabel>
    </miscellaneous>
    <aspectTypeRef href="urn:com.emc.ide.artifact.daspect/dm_logical_version?name=dm_logical_version#//@dataModel"/>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
