<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.moduledef/LifecycleScheduleOperation?name=LifecycleScheduleOperation" categoryId="com.emc.ide.artifact.moduledef" implicitlyCreated="true" modifiedByUser="false">
  <dataModel xsi:type="moduledef:ModuleDef" objectName="LifecycleScheduleOperation" title="" subject="" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" status="" min_dfc_version="6.0" implementation_technology="Java" contact_info="" a_bof_version="" a_module_type="[Standard Module]" module_description="">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_module?name=dmc_module#//@dataModel"/>
    <versionLabel>1.0</versionLabel>
    <versionLabel>CURRENT</versionLabel>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/lifecycle.jar?language_code=&amp;location=%2FSystem%2FModules%2FLifecycleBatchOperation&amp;name=lifecycle.jar&amp;type=dmc_jar#//@dataModel"/>
    <runtimeEnvironmentXML objectName="RuntimeEnvironment.xml" contentType="xml" rootObject="false" minDFCVersion="6.0" minVmVersion="1.5">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_sysobject?name=dm_sysobject#//@dataModel"/>
      <log message="" level="NONE"/>
    </runtimeEnvironmentXML>
    <primaryElement primary_class="com.documentum.server.impl.method.lifecycle.BPSchedule">
      <a_interfaces>com.documentum.fc.methodserver.IDfMethod</a_interfaces>
      <a_interfaces>com.documentum.fc.client.IDfModule</a_interfaces>
    </primaryElement>
    <miscellaneous objectName="Miscellaneous" title="" subject="" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" status="" rootObject="false">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_folder?name=dm_folder#//@dataModel"/>
      <versionLabel>1.0</versionLabel>
      <versionLabel>CURRENT</versionLabel>
    </miscellaneous>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
