<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:job="http://documentum.emc.com/artifact/12012007/job" urn="urn:com.emc.ide.artifact.job/dm_FTCreateEvents?location=%2FSystem%2FSysadmin%2FJobs&amp;name=dm_FTCreateEvents" categoryId="com.emc.ide.artifact.job" modifiedByUser="false">
  <dataModel xsi:type="job:Job" objectName="dm_FTCreateEvents" title="Fulltext" subject="Creates events for objects created/modified in between an IndexAgent migration and a complete upgrade" applicationType="" compoundArchitecture="" resolutionLabel="" contentType="" specialApp="" languageCode="" category="" controllingApp="" fullText="true" status="" passStandardArguments="true" runMode="Day(s)">
    <objectType href="urn:com.emc.ide.artifact.dclass/dm_job?name=dm_job#//@dataModel"/>
    <versionLabel>1.0</versionLabel>
    <versionLabel>CURRENT</versionLabel>
    <methodName href="urn:com.emc.ide.artifact.method/dm_FTCreateEvents?name=dm_FTCreateEvents#//@dataModel"/>
    <methodArguments>-window_interval 12000</methodArguments>
    <methodArguments>-queueperson dm_fulltext_index_user</methodArguments>
    <methodArguments>-max_events_per_run 50000</methodArguments>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
